'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'common.dashboard': 'Dashboard',
    'common.projects': 'Projects',
    'common.clients': 'Clients',
    'common.estimates': 'Estimates',
    'common.invoices': 'Invoices',
    'common.purchases': 'Purchases',
    'common.changeOrders': 'Change Orders',
    'common.reports': 'Reports',
    'common.settings': 'Settings',
    'common.new': 'New',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.print': 'Print',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.refresh': 'Refresh',
    'common.back': 'Back',
    'common.forward': 'Forward',
    'common.home': 'Home',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.help': 'Help',
    'common.support': 'Support',
    'common.documentation': 'Documentation',
    'common.tutorial': 'Tutorial',
    'common.faq': 'FAQ',
    'common.terms': 'Terms',
    'common.privacy': 'Privacy',
    'common.cookies': 'Cookies',
    'common.language': 'Language',
    'common.theme': 'Theme',
    'common.dark': 'Dark',
    'common.light': 'Light',
    'common.auto': 'Auto',
    'common.client': 'Client',
    'common.date': 'Date',
    'common.total': 'Total',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.type': 'Type',
    'common.email': 'Email',
    'common.project': 'Project',
    'navigation.dashboard': 'Dashboard',
    'navigation.projects': 'Projects',
    'navigation.clients': 'Clients',
    'navigation.estimates': 'Estimates',
    'navigation.invoices': 'Invoices',
    'navigation.purchases': 'Purchases',
    'navigation.changeOrders': 'Change Orders',
    'navigation.reports': 'Reports',
    'navigation.settings': 'Settings',
    'invoice.status.draft': 'Draft',
    'invoice.status.sent': 'Sent',
    'invoice.status.paid': 'Paid',
    'invoice.status.overdue': 'Overdue',
    'invoice.status.cancelled': 'Cancelled',
    'invoice.type.progress': 'Progress',
    'invoice.type.final': 'Final',
    'invoice.type.changeOrder': 'Change Order',
    'invoice.type.retainer': 'Retainer',
    'invoice.dueDate': 'Due Date',
    'invoice.invoiceNumber': 'Invoice Number',
    'invoice.issueDate': 'Issue Date',
    'invoice.paymentTerms': 'Payment Terms',
    'invoice.subtotal': 'Subtotal',
    'invoice.tax': 'Tax',
    'invoice.grandTotal': 'Grand Total',
    'invoice.type': 'Type',
    'invoice.status': 'Status',
    'invoice.client': 'Client',
    'invoice.project': 'Project',
    'invoice.items': 'Items',
    'invoice.description': 'Description',
    'invoice.quantity': 'Quantity',
    'invoice.unitPrice': 'Unit Price',
    'invoice.total': 'Total',
    'invoice.notes': 'Notes',
    'invoice.terms': 'Terms',
    'invoice.paymentMethod': 'Payment Method',
    'invoice.paymentDate': 'Payment Date',
    'invoice.amountPaid': 'Amount Paid',
    'invoice.balance': 'Balance',
    'invoice.paid': 'Paid',
    'invoice.pending': 'Pending',
    'invoice.overdue': 'Overdue',
    'invoice.cancelled': 'Cancelled',
    'invoice.draft': 'Draft',
    'invoice.sent': 'Sent',
    'invoice.progress': 'Progress',
    'invoice.final': 'Final',
    'invoice.changeOrder': 'Change Order',
    'invoice.retainer': 'Retainer',
    'invoice.cash': 'Cash',
    'invoice.check': 'Check',
    'invoice.creditCard': 'Credit Card',
    'invoice.bankTransfer': 'Bank Transfer',
    'invoice.other': 'Other',
    'purchases.newPurchase': 'New Purchase',
    'purchases.searchPlaceholder': 'Search purchases...',
    'purchase.category.materials': 'Materials',
    'purchase.category.equipment': 'Equipment',
    'purchase.category.labor': 'Labor',
    'purchase.category.permits': 'Permits',
    'purchase.category.other': 'Other',
    'purchases.noResults': 'No purchases found',
    'purchases.noPurchases': 'No purchases recorded',
    'purchases.tryOtherTerms': 'Try other search terms.',
    'purchases.startRecording': 'Start recording your first purchase.',
    'changeOrders.newChangeOrder': 'New Change Order',
    'changeOrders.searchChangeOrders': 'Search change orders',
    'changeOrders.searchPlaceholder': 'Search by title, project, client or number...',
    'changeOrders.changeOrder': 'Change Order',
    'changeOrders.amount': 'Amount',
    'changeOrders.approvalLink': 'Approval Link',
    'changeOrders.copyLink': 'Copy Link',
    'changeOrder.status.pending': 'Pending',
    'changeOrder.status.approved': 'Approved',
    'changeOrder.status.declined': 'Declined',
    'changeOrder.status.expired': 'Expired',
    'changeOrder.approve': 'Approve',
    'changeOrder.decline': 'Decline',
    'changeOrder.copyLink': 'Copy Link',
    'changeOrder.approvalLink': 'Approval Link',
    'changeOrder.policies': 'Change Order Policies',
    'changeOrder.policiesText': 'By clicking "Approve", you accept the change and the additional cost',
    'changeOrder.acceptPolicies': 'I accept the change order policies',
    'reports.last30Days': 'Last 30 days',
    'reports.totalRevenue': 'Total Revenue',
    'reports.activeProjects': 'Active Projects',
    'reports.completedProjects': 'Completed Projects',
    'reports.profitMargin': 'Profit Margin',
    'reports.financialSummary': 'Financial Summary',
    'reports.monthlyRevenue': 'Monthly Revenue',
    'reports.paidInvoices': 'Paid Invoices',
    'reports.pendingInvoices': 'Pending Invoices',
    'reports.totalProjects': 'Total Projects',
    'reports.changeOrders': 'Change Orders',
    'reports.totalOrders': 'Total Orders',
    'reports.approved': 'Approved',
    'reports.approvalRate': 'Approval Rate',
    'reports.pending': 'Pending',
    'reports.performanceIndicators': 'Performance Indicators',
    'reports.completionRate': 'Completion Rate',
    'reports.collectionRate': 'Collection Rate',
    'reports.changeApproval': 'Change Approval',
    'form.name': 'Name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.address': 'Address',
    'form.city': 'City',
    'form.state': 'State',
    'form.zipCode': 'Zip Code',
    'form.description': 'Description',
    'form.notes': 'Notes',
    'form.date': 'Date',
    'form.amount': 'Amount',
    'form.currency': 'Currency',
    'form.status': 'Status',
    'form.type': 'Type',
    'estimate.title': 'Estimate',
    'estimate.name': 'Estimate Name',
    'estimate.description': 'Description',
    'estimate.project': 'Project',
    'estimate.client': 'Client',
    'estimate.validUntil': 'Valid Until',
    'estimate.taxRate': 'Tax Rate',
    'estimate.terms': 'Payment Terms',
    'estimate.notes': 'Notes',
    'estimate.addItem': 'Add Item',
    'estimate.accept': 'Accept by Client',
    'project.title': 'Project',
    'project.name': 'Project Name',
    'project.description': 'Description',
    'project.client': 'Client',
    'project.startDate': 'Start Date',
    'project.endDate': 'End Date',
    'project.status': 'Status',
    'project.budget': 'Budget',
    'project.spent': 'Spent',
    'project.progress': 'Progress',
    'project.planning': 'Planning',
    'project.active': 'Active',
    'project.onHold': 'On Hold',
    'project.completed': 'Completed',
    'project.cancelled': 'Cancelled',
    'client.title': 'Client',
    'client.name': 'Client Name',
    'client.email': 'Email',
    'client.phone': 'Phone',
    'client.address': 'Address',
    'client.city': 'City',
    'client.state': 'State',
    'client.zipCode': 'Zip Code',
    'client.company': 'Company',
    'client.contact': 'Contact',
    'client.notes': 'Notes',
    'purchase.title': 'Purchase',
    'purchase.supplier': 'Supplier',
    'purchase.invoiceNumber': 'Invoice Number',
    'purchase.date': 'Date',
    'purchase.amount': 'Amount',
    'purchase.category': 'Category',
    'purchase.description': 'Description',
    'purchase.project': 'Project',
    'changeOrder.title': 'Change Order',
    'changeOrder.name': 'Change Order Name',
    'changeOrder.description': 'Description',
    'changeOrder.project': 'Project',
    'changeOrder.client': 'Client',
    'changeOrder.amount': 'Amount',
    'changeOrder.status': 'Status',
    'changeOrder.date': 'Date',
    'changeOrder.approved': 'Approved',
    'changeOrder.pending': 'Pending',
    'changeOrder.declined': 'Declined',
    'changeOrder.expired': 'Expired',
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Overview of your projects and activities',
    'dashboard.totalProjects': 'Total Projects',
    'dashboard.activeProjects': 'Active Projects',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.pendingInvoices': 'Pending Invoices',
    'dashboard.recentProjects': 'Recent Projects',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.newProject': 'New Project',
    'dashboard.createProject': 'Create a new construction project',
    'dashboard.createEstimate': 'Create Estimate',
    'dashboard.generateEstimate': 'Generate a new budget',
    'dashboard.newInvoice': 'New Invoice',
    'dashboard.createInvoice': 'Create an invoice for the client',
    'dashboard.addClient': 'Add Client',
    'dashboard.registerClient': 'Register a new client',
    'dashboard.invoiceSummary': 'Invoice Summary',
    'dashboard.viewAll': 'View all',
    'dashboard.totalInvoices': 'Total Invoices',
    'dashboard.totalBilled': 'Total Billed',
    'dashboard.pending': 'Pending',
    'dashboard.overdue': 'Overdue',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.noRecentActivity': 'No recent activity available',
    'reports.title': 'Reports',
    'reports.analyze': 'Analyze your project performance and profitability',
    'reports.refresh': 'Refresh',
    'reports.pdf': 'PDF',
    'reports.excel': 'Excel',
    'settings.title': 'Settings',
    'settings.configure': 'Configure your profile and application preferences',
    'settings.comingSoon': 'Coming Soon',
    'settings.workingOn': 'We are working on the application configuration.',
    'settings.configurationPanel': 'Configuration Panel'
  },
  es: {
    'common.dashboard': 'Dashboard',
    'common.projects': 'Proyectos',
    'common.clients': 'Clientes',
    'common.estimates': 'Estimados',
    'common.invoices': 'Facturas',
    'common.purchases': 'Compras',
    'common.changeOrders': 'Órdenes de Cambio',
    'common.reports': 'Reportes',
    'common.settings': 'Configuración',
    'common.new': 'Nuevo',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.warning': 'Advertencia',
    'common.info': 'Información',
    'common.previous': 'Anterior',
    'common.next': 'Siguiente',
    'common.close': 'Cerrar',
    'common.open': 'Abrir',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.import': 'Importar',
    'common.print': 'Imprimir',
    'common.download': 'Descargar',
    'common.upload': 'Subir',
    'common.refresh': 'Actualizar',
    'common.back': 'Atrás',
    'common.forward': 'Adelante',
    'common.home': 'Inicio',
    'common.about': 'Acerca de',
    'common.contact': 'Contacto',
    'common.help': 'Ayuda',
    'common.support': 'Soporte',
    'common.documentation': 'Documentación',
    'common.tutorial': 'Tutorial',
    'common.faq': 'Preguntas Frecuentes',
    'common.terms': 'Términos',
    'common.privacy': 'Privacidad',
    'common.cookies': 'Cookies',
    'common.language': 'Idioma',
    'common.theme': 'Tema',
    'common.dark': 'Oscuro',
    'common.light': 'Claro',
    'common.auto': 'Automático',
    'common.client': 'Cliente',
    'common.date': 'Fecha',
    'common.total': 'Total',
    'common.status': 'Estado',
    'common.actions': 'Acciones',
    'common.type': 'Tipo',
    'common.email': 'Correo',
    'common.project': 'Proyecto',
    'navigation.dashboard': 'Dashboard',
    'navigation.projects': 'Proyectos',
    'navigation.clients': 'Clientes',
    'navigation.estimates': 'Estimados',
    'navigation.invoices': 'Facturas',
    'navigation.purchases': 'Compras',
    'navigation.changeOrders': 'Órdenes de Cambio',
    'navigation.reports': 'Reportes',
    'navigation.settings': 'Configuración',
    'invoice.status.draft': 'Borrador',
    'invoice.status.sent': 'Enviada',
    'invoice.status.paid': 'Pagada',
    'invoice.status.overdue': 'Vencida',
    'invoice.status.cancelled': 'Cancelada',
    'invoice.type.progress': 'Progreso',
    'invoice.type.final': 'Final',
    'invoice.type.changeOrder': 'Orden de Cambio',
    'invoice.type.retainer': 'Retainer',
    'invoice.dueDate': 'Fecha de Vencimiento',
    'invoice.invoiceNumber': 'Número de Factura',
    'invoice.issueDate': 'Fecha de Emisión',
    'invoice.paymentTerms': 'Términos de Pago',
    'invoice.subtotal': 'Subtotal',
    'invoice.tax': 'Impuesto',
    'invoice.grandTotal': 'Total',
    'invoice.type': 'Tipo',
    'invoice.status': 'Estado',
    'invoice.client': 'Cliente',
    'invoice.project': 'Proyecto',
    'invoice.items': 'Items',
    'invoice.description': 'Descripción',
    'invoice.quantity': 'Cantidad',
    'invoice.unitPrice': 'Precio Unitario',
    'invoice.total': 'Total',
    'invoice.notes': 'Notas',
    'invoice.terms': 'Términos',
    'invoice.paymentMethod': 'Método de Pago',
    'invoice.paymentDate': 'Fecha de Pago',
    'invoice.amountPaid': 'Monto Pagado',
    'invoice.balance': 'Balance',
    'invoice.paid': 'Pagada',
    'invoice.pending': 'Pendiente',
    'invoice.overdue': 'Vencida',
    'invoice.cancelled': 'Cancelada',
    'invoice.draft': 'Borrador',
    'invoice.sent': 'Enviada',
    'invoice.progress': 'Progreso',
    'invoice.final': 'Final',
    'invoice.changeOrder': 'Orden de Cambio',
    'invoice.retainer': 'Retainer',
    'invoice.cash': 'Efectivo',
    'invoice.check': 'Cheque',
    'invoice.creditCard': 'Tarjeta de Crédito',
    'invoice.bankTransfer': 'Transferencia Bancaria',
    'invoice.other': 'Otro',
    'purchases.newPurchase': 'Nueva Compra',
    'purchases.searchPlaceholder': 'Buscar compras...',
    'purchase.category.materials': 'Materiales',
    'purchase.category.equipment': 'Equipos',
    'purchase.category.labor': 'Mano de Obra',
    'purchase.category.permits': 'Permisos',
    'purchase.category.other': 'Otros',
    'purchases.noResults': 'No se encontraron compras',
    'purchases.noPurchases': 'No hay compras registradas',
    'purchases.tryOtherTerms': 'Prueba con otros términos de búsqueda.',
    'purchases.startRecording': 'Comienza registrando tu primera compra.',
    'changeOrders.newChangeOrder': 'Nueva Orden de Cambio',
    'changeOrders.searchChangeOrders': 'Buscar órdenes de cambio',
    'changeOrders.searchPlaceholder': 'Buscar por título, proyecto, cliente o número...',
    'changeOrders.changeOrder': 'Orden de Cambio',
    'changeOrders.amount': 'Monto',
    'changeOrders.approvalLink': 'Enlace de Aprobación',
    'changeOrders.copyLink': 'Copiar Enlace',
    'changeOrder.status.pending': 'Pendiente',
    'changeOrder.status.approved': 'Aprobado',
    'changeOrder.status.declined': 'Rechazado',
    'changeOrder.status.expired': 'Expirado',
    'changeOrder.approve': 'Aprobar',
    'changeOrder.decline': 'Rechazar',
    'changeOrder.copyLink': 'Copiar Enlace',
    'changeOrder.approvalLink': 'Enlace de Aprobación',
    'changeOrder.policies': 'Políticas de Orden de Cambio',
    'changeOrder.policiesText': 'Al hacer clic en "Aprobar", aceptas el cambio y el costo adicional',
    'changeOrder.acceptPolicies': 'Acepto las políticas de orden de cambio',
    'reports.last30Days': 'Últimos 30 días',
    'reports.totalRevenue': 'Ingresos Totales',
    'reports.activeProjects': 'Proyectos Activos',
    'reports.completedProjects': 'Proyectos Completados',
    'reports.profitMargin': 'Margen de Ganancia',
    'reports.financialSummary': 'Resumen Financiero',
    'reports.monthlyRevenue': 'Ingresos del Mes',
    'reports.paidInvoices': 'Facturas Pagadas',
    'reports.pendingInvoices': 'Facturas Pendientes',
    'reports.totalProjects': 'Total Proyectos',
    'reports.changeOrders': 'Órdenes de Cambio',
    'reports.totalOrders': 'Total Órdenes',
    'reports.approved': 'Aprobadas',
    'reports.approvalRate': 'Tasa de Aprobación',
    'reports.pending': 'Pendientes',
    'reports.performanceIndicators': 'Indicadores de Rendimiento',
    'reports.completionRate': 'Tasa de Finalización',
    'reports.collectionRate': 'Tasa de Cobro',
    'reports.changeApproval': 'Aprobación de Cambios',
    'form.name': 'Nombre',
    'form.email': 'Correo',
    'form.phone': 'Teléfono',
    'form.address': 'Dirección',
    'form.city': 'Ciudad',
    'form.state': 'Estado',
    'form.zipCode': 'Código Postal',
    'form.description': 'Descripción',
    'form.notes': 'Notas',
    'form.date': 'Fecha',
    'form.amount': 'Monto',
    'form.currency': 'Moneda',
    'form.status': 'Estado',
    'form.type': 'Tipo',
    'estimate.title': 'Estimado',
    'estimate.name': 'Nombre del Estimado',
    'estimate.description': 'Descripción',
    'estimate.project': 'Proyecto',
    'estimate.client': 'Cliente',
    'estimate.validUntil': 'Válido Hasta',
    'estimate.taxRate': 'Tasa de Impuesto',
    'estimate.terms': 'Términos de Pago',
    'estimate.notes': 'Notas',
    'estimate.addItem': 'Agregar Item',
    'estimate.accept': 'Aceptar por Cliente',
    'project.title': 'Proyecto',
    'project.name': 'Nombre del Proyecto',
    'project.description': 'Descripción',
    'project.client': 'Cliente',
    'project.startDate': 'Fecha de Inicio',
    'project.endDate': 'Fecha de Fin',
    'project.status': 'Estado',
    'project.budget': 'Presupuesto',
    'project.spent': 'Gastado',
    'project.progress': 'Progreso',
    'project.planning': 'Planificación',
    'project.active': 'Activo',
    'project.onHold': 'En Pausa',
    'project.completed': 'Completado',
    'project.cancelled': 'Cancelado',
    'client.title': 'Cliente',
    'client.name': 'Nombre del Cliente',
    'client.email': 'Correo',
    'client.phone': 'Teléfono',
    'client.address': 'Dirección',
    'client.city': 'Ciudad',
    'client.state': 'Estado',
    'client.zipCode': 'Código Postal',
    'client.company': 'Empresa',
    'client.contact': 'Contacto',
    'client.notes': 'Notas',
    'purchase.title': 'Compra',
    'purchase.supplier': 'Proveedor',
    'purchase.invoiceNumber': 'Número de Factura',
    'purchase.date': 'Fecha',
    'purchase.amount': 'Monto',
    'purchase.category': 'Categoría',
    'purchase.description': 'Descripción',
    'purchase.project': 'Proyecto',
    'changeOrder.title': 'Orden de Cambio',
    'changeOrder.name': 'Nombre de la Orden de Cambio',
    'changeOrder.description': 'Descripción',
    'changeOrder.project': 'Proyecto',
    'changeOrder.client': 'Cliente',
    'changeOrder.amount': 'Monto',
    'changeOrder.status': 'Estado',
    'changeOrder.date': 'Fecha',
    'changeOrder.approved': 'Aprobado',
    'changeOrder.pending': 'Pendiente',
    'changeOrder.declined': 'Rechazado',
    'changeOrder.expired': 'Expirado',
    'dashboard.title': 'Dashboard',
    'dashboard.overview': 'Resumen general de tus proyectos y actividades',
    'dashboard.totalProjects': 'Total Proyectos',
    'dashboard.activeProjects': 'Proyectos Activos',
    'dashboard.totalRevenue': 'Ingresos Totales',
    'dashboard.pendingInvoices': 'Facturas Pendientes',
    'dashboard.recentProjects': 'Proyectos Recientes',
    'dashboard.quickActions': 'Acciones Rápidas',
    'dashboard.newProject': 'Nuevo Proyecto',
    'dashboard.createProject': 'Crear un nuevo proyecto de construcción',
    'dashboard.createEstimate': 'Crear Estimado',
    'dashboard.generateEstimate': 'Generar un nuevo presupuesto',
    'dashboard.newInvoice': 'Nueva Factura',
    'dashboard.createInvoice': 'Crear una factura para el cliente',
    'dashboard.addClient': 'Agregar Cliente',
    'dashboard.registerClient': 'Registrar un nuevo cliente',
    'dashboard.invoiceSummary': 'Resumen de Facturación',
    'dashboard.viewAll': 'Ver todas',
    'dashboard.totalInvoices': 'Total Facturas',
    'dashboard.totalBilled': 'Total Facturado',
    'dashboard.pending': 'Pendiente',
    'dashboard.overdue': 'Vencida',
    'dashboard.recentActivity': 'Actividad Reciente',
    'dashboard.noRecentActivity': 'No hay actividad reciente disponible',
    'reports.title': 'Reportes',
    'reports.analyze': 'Analiza el rendimiento de tus proyectos y la rentabilidad',
    'reports.refresh': 'Actualizar',
    'reports.pdf': 'PDF',
    'reports.excel': 'Excel',
    'settings.title': 'Configuración',
    'settings.configure': 'Configura tu perfil y preferencias de la aplicación',
    'settings.comingSoon': 'Próximamente',
    'settings.workingOn': 'Estamos trabajando en la configuración de la aplicación.',
    'settings.configurationPanel': 'Panel de Configuración'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState('es');

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language');
      if (savedLanguage) {
        setLanguage(savedLanguage);
      }
    }
  }, []);

  const handleSetLanguage = (lang: string) => {
    setLanguage(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    const langTranslations = translations[language as keyof typeof translations];
    return (langTranslations as any)?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}